
### Get from monitored table
GET http://localhost:7071/api/db/monitored HTTP/1.1


### Get from target table
GET http://localhost:7071/api/db/target HTTP/1.1

### Add data to monitored table
POST http://localhost:7071/api/db/monitored HTTP/1.1
content-type: application/json

{
    "name": "yo yo go climbing"
}

### Enqueue
POST http://localhost:7071/api/queue
content-type: application/json

{
    "name": "yo yo"
}

